language: php

php:
    - 5.4
    - 5.5
    - 5.6

install:
    - composer install
    - npm install

before_script:
    - make phantomjs
    - curl -O http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar

script:
    - php bin/phpunit -c build/
    - php bin/phpcs -n --standard=PSR1,PSR2 --report=full src/
    - java -jar selenium-server-standalone-2.44.0.jar
    - php bin/behat test/integrations

after_script:
    - ls -alh build/logs
    - php bin/coveralls -v

notifications:
    email: true

matrix:
    fast_finish: true

# Only build the master branch and pull requests for the master branch
branches:
    only:
        - master
