language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

install: composer install

script:
    - php bin/phpunit -c build/
    - php bin/phpcs -n --standard=PSR1,PSR2 --report=full src/
      #- php bin/phpmd src/ text build/rulesets/phpmd.xml

notifications:
    email: true

matrix:
    fast_finish: true
    allow_failures:
        - php: 5.3
